- name: Set up a new Linux Mint or Ubuntu system.
  hosts: localhost
  connection: local

  vars:
    HOMEDIR: "{{ ansible_env.HOME }}"
    BINDIR: "{{ HOMEDIR }}/bin"
    PROGSDIR: "{{ HOMEDIR }}/progs"
    PPAS:
      - ppa:inkscape.dev/stable
      - ppa:qbittorrent-team/qbittorrent-stable
      - ppa:git-core/ppa
    TEMPDIR: ./temp

  tasks:

  - name: Create $HOME/bin if it does not exist
    file:
      path: "{{ BINDIR }}"
      state: directory

  - name: Add $HOME/bin to $PATH.
    lineinfile:
      path: "{{ HOMEDIR }}/.pam_environment"
      line: "PATH DEFAULT=${PATH}:{{ BINDIR }}"

  - name: Add extra APT repositories
    apt_repository:
      repo: "{{ item }}"
      codename: "focal"
      state: present
      update_cache: no
    loop: "{{ PPAS }}"
    become: yes

  - name: Include list of packages
    include_vars:
      file: packages.yml
      name: package_list

  - name: Install packages
    apt:
      name: "{{ package_list.packages }}"
      state: present
      update_cache: yes
    become: yes

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
    become: yes

  #########################################
  # From here on we install and configure #
  # stuff # that requires special steps.  #
  #########################################

  - name: Create temporary directory to store downloaded files
    file:
      path: "{{ TEMPDIR }}"
      state: directory

  - name: libdvd-pkg needs dpkg-reconfigure
    command:
      cmd: dpkg-reconfigure -f noninteractive libdvd-pkg
    become: yes

  ##############################
  # Hugo static site generator #
  ##############################
  - name: Get the URL for the latest version of Hugo from Github
    shell: |
      curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest \
      | jq '.assets[].browser_download_url
      | select(endswith("Linux-64bit.deb"))
      | select(contains("extended"))
      | {url: ., filename: split("/")[-1]}'
    register: hugo_version
  - debug: msg="{{ hugo_version.stdout }}"

  - name: Download the latest version of Hugo to a temporary file
    get_url:
      url: "{{ (hugo_version.stdout | from_json).url }}"
      dest: "{{ TEMPDIR }}/{{ (hugo_version.stdout | from_json).filename }}"

  - name: Install the latest version of Hugo from the temporary file
    apt:
      deb: "{{ TEMPDIR }}/{{ (hugo_version.stdout | from_json).filename }}"
    become: yes



  ###################
  # DBeaver flatpak #
  ###################
  - name: Install the DBeaver flatpak
    community.general.flatpak:
      name: io.dbeaver.DBeaverCommunity
      state: present

  #########################
  # Install Google Chrome #
  #########################
  - name: Install Google Chrome
    apt:
      deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    become: yes


  - name: Remove packages not needed anymore
    apt:
      autoremove: yes
    become: yes

  - name: Remove temporary directory to store downloaded files
    file:
      path: "{{ TEMPDIR }}"
      state: absent
