- name: Set up a new Linux Mint or Ubuntu system.
  hosts: localhost
  connection: local

  vars:
    HOMEDIR: "{{ ansible_env.HOME }}"
    BINDIR: "{{ HOMEDIR }}/bin"
    PROGSDIR: "{{ HOMEDIR }}/progs"
    REPOS:
      - ppa:inkscape.dev/stable
      - ppa:qbittorrent-team/qbittorrent-stable
      - ppa:git-core/ppa
      - deb https://dl.google.com/linux/chrome/deb/ stable main
    TEMPDIR: ./temp
    CODENAME: focal


  tasks:

  - name: Create $HOME/bin if it does not exist
    file:
      path: "{{ BINDIR }}"
      state: directory

  - name: Add $HOME/bin to $PATH.
    lineinfile:
      path: "{{ HOMEDIR }}/.pam_environment"
      line: "PATH DEFAULT=${PATH}:{{ BINDIR }}"
      create: yes


  - name: Add extra APT repositories
    apt_repository:
      repo: "{{ item }}"
      codename: "focal"
      state: present
      update_cache: no
    loop: "{{ REPOS }}"
    become: yes

  - name: Add Google APT signing key
    apt_key:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      state: present
    become: yes

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest
      update_cache: yes
    become: yes

  - name: Include list of packages
    include_vars:
      file: packages.yml
      name: package_list

  - name: Install packages
    apt:
      name: "{{ package_list.packages }}"
      state: present
      update_cache: yes
    become: yes

  #########################################
  # From here on we install and configure #
  # stuff # that requires special steps.  #
  #########################################

  - name: Create temporary directory to store downloaded files
    file:
      path: "{{ TEMPDIR }}"
      state: directory

  - name: libdvd-pkg needs dpkg-reconfigure
    command:
      cmd: dpkg-reconfigure -f noninteractive libdvd-pkg
    become: yes

  ######################
  # ZShell and friends #
  ######################
  - name: Download Oh My Zsh installer
    get_url:
      url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: "{{ TEMPDIR }}/install-oh-my-zsh.sh"

  - name: Install Oh My Zsh
    script: "{{ TEMPDIR }}/install-oh-my-zsh.sh"

  - name: Add config to .zshrc
    blockinfile:
      path: "{{ HOMEDIR }}/.zshrc"
      block: |
        export PATH="{{ HOMEDIR }}/.pyenv/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"


  ##############################
  # Hugo static site generator #
  ##############################
  - name: Get the URL for the latest version of Hugo from Github
    shell: |
      curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest \
      | jq '.assets[].browser_download_url
      | select(endswith("Linux-64bit.deb"))
      | select(contains("extended"))
      | {url: ., filename: split("/")[-1]}'
    register: hugo_version
  - debug: msg="{{ hugo_version.stdout }}"

  - name: Download the latest version of Hugo to a temporary file
    get_url:
      url: "{{ (hugo_version.stdout | from_json).url }}"
      dest: "{{ TEMPDIR }}/{{ (hugo_version.stdout | from_json).filename }}"

  - name: Install the latest version of Hugo from the temporary file
    apt:
      deb: "{{ TEMPDIR }}/{{ (hugo_version.stdout | from_json).filename }}"
    become: yes



  ###################
  # DBeaver flatpak #
  ###################
  - name: Install the DBeaver flatpak
    community.general.flatpak:
      name: io.dbeaver.DBeaverCommunity
      state: present


  #####################
  # Git configuration #
  #####################
  - name: Add git up alias
    community.general.git_config:
      name: alias.up
      scope: global
      value: pull --rebase --autostash

  - name: Set commit signing key
    community.general.git_config:
      name: user.signingkey
      scope: global
      value: 56BF26D22EED3B43

  - name: Activate commit signing
    community.general.git_config:
      name: commit.gpgSign
      scope: global
      value: true

  ################
  # Python stuff #
  ################
  - name: Install pipx
    pip:
      name: pipx
      extra_args: --user

  - name: Download pyenv installer
    get_url:
      url: https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
      dest: "{{ TEMPDIR }}/pyenv-installer"
      mode: u+rwx
  - name: Install pyenv
    script: "{{ TEMPDIR }}/pyenv-installer"

  - name: Download Poetry installer
    get_url:
      url: https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
      dest: "{{ TEMPDIR }}/get-poetry.py"
      mode: u+rwx

  - name: Install Poetry
    script: "{{ TEMPDIR }}/get-poetry.py"





  - name: Remove packages not needed anymore
    apt:
      autoremove: yes
    become: yes

  - name: Remove temporary directory to store downloaded files
    file:
      path: "{{ TEMPDIR }}"
      state: absent
